---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for Bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for Elm
  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for git submodule
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for Mix
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"
