version = 1

exclude_patterns = [
  "**/*copilot*",
  "**/*vscode*",
  "**/.git/*",
  "**/Application Support/*",
  "**/archive/*",
  "**/custom/plugins/*",
  "**/custom/themes/*",
  "**/node_modules/*",
  "**/package-lock.json",
  "**/t/*",
  "**/Test*",
  "**/test*"
]

[[analyzers]]
name = "ansible"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "java"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  style_guide = "standard"
  environment = ["browser"]

[[transformers]]
name = "standardjs"
enabled = true

[[analyzers]]
name = "php"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

[[analyzers]]
name = "scala"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
