---
# Issue template
# https://web.archive.org/web/20200705094743id_/docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: Bug report
    url: bug_report.md
    about: Please report project-specific bugs here.
  - name: Feature request
    url: feature_request.md
    about: Please submit new feature ideas here.
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
